<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>R</string>
		<string>r</string>
		<string>s</string>
		<string>S</string>
		<string>Rprofile</string>
		<string>Rhistory</string>
		<string>history</string>
		<string>log</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[^#]*(\([^\)]*$|\{\s*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\)|^\s*\})</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>roxygen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.roxcomment.r</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#+').*$\n?</string>
			<key>name</key>
			<string>comment.documentation.roxyen.r</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\link\{\code</string>
			<key>name</key>
			<string>invalid.illegal.linkcode.r</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)(?:tabular))(\{)(?:\n)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.examples.rd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.rd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.rd</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.r.embedded</string>
			<key>end</key>
			<string>(^#' \}$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.rd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.documentation.roxyen.tabular.rox</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.r</string>
	<key>uuid</key>
	<string>E6F2E33D-847A-491F-9F2A-DBA96F30BBAB</string>
</dict>
</plist>
